export const TestData = [
  {
    id: 51,
    mainRecipeName: "Chicken Parmesan",
    recipeTypeSelectedValue: ["Italian"],
    totalTimeMinutes: 60,
    ingredientsArray: [
      "Chicken breasts",
      "Bread crumbs",
      "Tomato sauce",
      "Mozzarella cheese",
    ],
    recipeStatus: "classic",
    recipeRating: 4.5,
    recipePrice: 3,
    recipeDirections:
      "Preheat oven to 375°F. Bread chicken and bake for 25 minutes. Top with sauce and cheese. Bake for an additional 10 minutes until cheese is melted and bubbly.",
  },
  {
    id: 52,
    mainRecipeName: "Spaghetti Bolognese",
    recipeTypeSelectedValue: ["Italian"],
    totalTimeMinutes: 45,
    ingredientsArray: [
      "Ground beef",
      "Tomato sauce",
      "Onion",
      "Garlic",
      "Spaghetti",
    ],
    recipeStatus: "classic",
    recipeRating: 4.2,
    recipePrice: 2,
    recipeDirections:
      "Cook spaghetti according to package instructions. Brown ground beef with onion and garlic. Add tomato sauce and simmer for 20 minutes. Serve over cooked spaghetti.",
  },
  {
    id: 53,
    mainRecipeName: "Taco Salad",
    recipeTypeSelectedValue: ["Mexican"],
    totalTimeMinutes: 30,
    ingredientsArray: [
      "Ground beef",
      "Lettuce",
      "Tomatoes",
      "Cheese",
      "Tortilla chips",
      "Sour cream",
      "Salsa",
    ],
    recipeStatus: "classic",
    recipeRating: 4.7,
    recipePrice: 2,
    recipeDirections:
      "Brown ground beef and season with taco seasoning. Arrange lettuce, tomatoes, cheese, and tortilla chips on a plate. Top with ground beef, sour cream, and salsa.",
  },
  {
    id: 54,
    mainRecipeName: "Mushroom Risotto",
    recipeTypeSelectedValue: ["Italian"],
    totalTimeMinutes: 50,
    ingredientsArray: [
      "Arborio rice",
      "Mushrooms",
      "Onion",
      "Garlic",
      "Vegetable broth",
      "Parmesan cheese",
    ],
    recipeStatus: "classic",
    recipeRating: 4.3,
    recipePrice: 3,
    recipeDirections:
      "Sauté mushrooms, onion, and garlic. Add Arborio rice and cook until translucent. Gradually add vegetable broth and cook until rice is tender. Stir in Parmesan cheese before serving.",
  },
  {
    id: 55,
    mainRecipeName: "BBQ Pulled Pork Sandwich",
    recipeTypeSelectedValue: ["American"],
    totalTimeMinutes: 360,
    ingredientsArray: [
      "Pork shoulder",
      "BBQ sauce",
      "Hamburger buns",
      "Coleslaw",
    ],
    recipeStatus: "classic",
    recipeRating: 4.6,
    recipePrice: 3,
    recipeDirections:
      "Rub pork shoulder with spices and slow-cook in a crockpot for 6-8 hours. Shred the cooked pork and mix with BBQ sauce. Serve on hamburger buns with coleslaw.",
  },
  {
    id: 56,
    mainRecipeName: "Caesar Salad",
    recipeTypeSelectedValue: ["Salad"],
    totalTimeMinutes: 20,
    ingredientsArray: [
      "Romaine lettuce",
      "Croutons",
      "Parmesan cheese",
      "Caesar dressing",
    ],
    recipeStatus: "classic",
    recipeRating: 4.4,
    recipePrice: 2,
    recipeDirections:
      "Tear lettuce into bite-sized pieces. Toss with croutons, Parmesan cheese, and Caesar dressing. Serve immediately.",
  },
  {
    id: 57,
    mainRecipeName: "Beef Stir-Fry",
    recipeTypeSelectedValue: ["Asian"],
    totalTimeMinutes: 25,
    ingredientsArray: [
      "Beef strips",
      "Mixed vegetables",
      "Soy sauce",
      "Ginger",
      "Garlic",
      "Rice",
    ],
    recipeStatus: "classic",
    recipeRating: 4.1,
    recipePrice: 3,
    recipeDirections:
      "Stir-fry beef strips with ginger and garlic. Add mixed vegetables and cook until tender. Season with soy sauce. Serve over cooked rice.",
  },
  {
    id: 58,
    mainRecipeName: "Margherita Pizza",
    recipeTypeSelectedValue: ["Italian"],
    totalTimeMinutes: 30,
    ingredientsArray: [
      "Pizza dough",
      "Tomato sauce",
      "Fresh mozzarella cheese",
      "Basil leaves",
      "Olive oil",
    ],
    recipeStatus: "classic",
    recipeRating: 4.8,
    recipePrice: 2,
    recipeDirections:
      "Roll out pizza dough and top with tomato sauce, mozzarella cheese, and basil leaves. Drizzle with olive oil. Bake in a preheated oven at 450°F for 12-15 minutes.",
  },
  {
    id: 59,
    mainRecipeName: "Lemon Garlic Shrimp",
    recipeTypeSelectedValue: ["Seafood"],
    totalTimeMinutes: 15,
    ingredientsArray: ["Shrimp", "Lemon juice", "Garlic", "Butter", "Parsley"],
    recipeStatus: "classic",
    recipeRating: 4.5,
    recipePrice: 3,
    recipeDirections:
      "Sauté shrimp in butter and garlic. Add lemon juice and parsley. Cook until shrimp is pink and opaque. Serve hot.",
  },
  {
    id: 510,
    mainRecipeName: "Beef Tacos",
    recipeTypeSelectedValue: ["Mexican"],
    totalTimeMinutes: 40,
    ingredientsArray: [
      "Ground beef",
      "Taco seasoning",
      "Tortillas",
      "Lettuce",
      "Tomatoes",
      "Cheese",
      "Sour cream",
      "Salsa",
    ],
    recipeStatus: "classic",
    recipeRating: 4.3,
    recipePrice: 2,
    recipeDirections:
      "Brown ground beef and season with taco seasoning. Heat tortillas and assemble tacos with beef, lettuce, tomatoes, cheese, sour cream, and salsa.",
  },
  {
    id: 511,
    mainRecipeName: "Pasta Carbonara",
    recipeTypeSelectedValue: ["Italian"],
    totalTimeMinutes: 30,
    ingredientsArray: [
      "Spaghetti",
      "Bacon",
      "Eggs",
      "Parmesan cheese",
      "Black pepper",
    ],
    recipeStatus: "classic",
    recipeRating: 4.7,
    recipePrice: 2,
    recipeDirections:
      "Cook spaghetti according to package instructions. Sauté bacon until crispy. In a separate bowl, whisk eggs, Parmesan cheese, and black pepper. Drain cooked spaghetti and toss with the egg mixture and bacon. Serve immediately.",
  },
  {
    id: 512,
    mainRecipeName: "Chicken Curry",
    recipeTypeSelectedValue: ["Asian"],
    totalTimeMinutes: 45,
    ingredientsArray: [
      "Chicken thighs",
      "Curry powder",
      "Coconut milk",
      "Onion",
      "Garlic",
      "Ginger",
      "Rice",
    ],
    recipeStatus: "classic",
    recipeRating: 4.6,
    recipePrice: 3,
    recipeDirections:
      "Sauté chicken thighs with onion, garlic, and ginger. Add curry powder and cook for a few minutes. Pour in coconut milk and simmer until chicken is cooked through. Serve over cooked rice.",
  },
  {
    id: 513,
    mainRecipeName: "Caprese Salad",
    recipeTypeSelectedValue: ["Salad"],
    totalTimeMinutes: 10,
    ingredientsArray: [
      "Tomatoes",
      "Fresh mozzarella cheese",
      "Basil leaves",
      "Balsamic vinegar",
      "Olive oil",
    ],
    recipeStatus: "classic",
    recipeRating: 4.2,
    recipePrice: 2,
    recipeDirections:
      "Slice tomatoes and fresh mozzarella cheese. Arrange on a plate with basil leaves. Drizzle with balsamic vinegar and olive oil. Season with salt and pepper.",
  },
  {
    id: 514,
    mainRecipeName: "Teriyaki Chicken",
    recipeTypeSelectedValue: ["Asian"],
    totalTimeMinutes: 35,
    ingredientsArray: [
      "Chicken breasts",
      "Teriyaki sauce",
      "Soy sauce",
      "Honey",
      "Garlic",
      "Ginger",
      "Green onions",
      "Rice",
    ],
    recipeStatus: "classic",
    recipeRating: 4.4,
    recipePrice: 3,
    recipeDirections:
      "Marinate chicken breasts in teriyaki sauce, soy sauce, honey, garlic, and ginger. Grill or bake until cooked through. Slice and garnish with green onions. Serve over cooked rice.",
  },
  {
    id: 515,
    mainRecipeName: "Vegetable Lasagna",
    recipeTypeSelectedValue: ["Italian"],
    totalTimeMinutes: 60,
    ingredientsArray: [
      "Lasagna noodles",
      "Zucchini",
      "Yellow squash",
      "Spinach",
      "Ricotta cheese",
      "Marinara sauce",
      "Mozzarella cheese",
    ],
    recipeStatus: "classic",
    recipeRating: 4.1,
    recipePrice: 2,
    recipeDirections:
      "Boil lasagna noodles until al dente. Sauté zucchini, yellow squash, and spinach. In a baking dish, layer noodles, vegetables, ricotta cheese, and marinara sauce. Repeat the layers and top with mozzarella cheese. Bake in a preheated oven at 375°F for 30 minutes.",
  },
  {
    id: 516,
    mainRecipeName: "Fish Tacos",
    recipeTypeSelectedValue: ["Seafood"],
    totalTimeMinutes: 35,
    ingredientsArray: [
      "White fish fillets",
      "Lime juice",
      "Cabbage",
      "Cilantro",
      "Corn tortillas",
      "Sour cream",
      "Salsa",
    ],
    recipeStatus: "classic",
    recipeRating: 4.8,
    recipePrice: 2,
    recipeDirections:
      "Marinate white fish fillets in lime juice. Grill or bake until cooked through. Flake the fish and assemble tacos with cabbage, cilantro, corn tortillas, sour cream, and salsa.",
  },
  {
    id: 517,
    mainRecipeName: "Chicken Alfredo",
    recipeTypeSelectedValue: ["Italian"],
    totalTimeMinutes: 40,
    ingredientsArray: [
      "Chicken breasts",
      "Fettuccine pasta",
      "Alfredo sauce",
      "Parmesan cheese",
      "Garlic",
      "Butter",
    ],
    recipeStatus: "classic",
    recipeRating: 4.5,
    recipePrice: 3,
    recipeDirections:
      "Grill or sauté chicken breasts until cooked through. Cook fettuccine pasta until al dente. In a separate pan, melt butter and sauté garlic. Add Alfredo sauce and heat until warm. Toss cooked pasta in the sauce. Serve with sliced chicken breasts and grated Parmesan cheese.",
  },
  {
    id: 518,
    mainRecipeName: "Shrimp Fried Rice",
    recipeTypeSelectedValue: ["Asian"],
    totalTimeMinutes: 25,
    ingredientsArray: [
      "Shrimp",
      "Rice",
      "Frozen mixed vegetables",
      "Eggs",
      "Soy sauce",
      "Sesame oil",
      "Green onions",
    ],
    recipeStatus: "classic",
    recipeRating: 4.3,
    recipePrice: 2,
    recipeDirections:
      "Cook rice according to package instructions. Sauté shrimp, mixed vegetables, and green onions. Push the mixture to one side and scramble eggs on the other side. Stir in cooked rice and season with soy sauce and sesame oil. Cook until heated through.",
  },
  {
    id: 519,
    mainRecipeName: "Greek Salad",
    recipeTypeSelectedValue: ["Salad"],
    totalTimeMinutes: 15,
    ingredientsArray: [
      "Lettuce",
      "Tomatoes",
      "Cucumbers",
      "Red onions",
      "Kalamata olives",
      "Feta cheese",
      "Olive oil",
      "Red wine vinegar",
    ],
    recipeStatus: "classic",
    recipeRating: 4.7,
    recipePrice: 2,
    recipeDirections:
      "Tear lettuce into bite-sized pieces. Chop tomatoes, cucumbers, and red onions. Combine with Kalamata olives and crumbled feta cheese. Drizzle with olive oil and red wine vinegar. Season with salt and pepper.",
  },
  {
    id: 520,
    mainRecipeName: "Honey Garlic Salmon",
    recipeTypeSelectedValue: ["Seafood"],
    totalTimeMinutes: 30,
    ingredientsArray: [
      "Salmon fillets",
      "Honey",
      "Soy sauce",
      "Garlic",
      "Lemon juice",
      "Butter",
    ],
    recipeStatus: "classic",
    recipeRating: 4.6,
    recipePrice: 3,
    recipeDirections:
      "Preheat oven to 400°F. In a small bowl, whisk together honey, soy sauce, garlic, and lemon juice. Place salmon fillets on a baking sheet and pour the sauce over them. Bake for 15-20 minutes until salmon is cooked through. Serve hot.",
  },
];
